FROM node:18

WORKDIR /app

COPY apps/oss ./apps/oss
WORKDIR /app/apps/oss

RUN corepack enable && corepack prepare pnpm@latest --activate
RUN pnpm install
RUN pnpm build

EXPOSE 3000
CMD ["pnpm", "preview"]
